# Nixpacks Configuration for Railway
# https://nixpacks.com/docs/configuration

[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --omit=dev"]

[phases.build]
cmds = []

[start]
cmd = "npm start"
